using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace TriLibCore.Interfaces
{
    /// <summary>
    /// Represents a TriLib Geometry Group. A Geometry Group contains child Geometries.
    /// </summary>
    public interface IGeometryGroup : IObject
    {
        /// <summary>
        /// Gets/Sets the Blend-Shape keys in this group.
        /// </summary>
        List<IBlendShapeKey> BlendShapeKeys { get; set; }

        /// <summary>
        /// Gets/Sets the Geometries in this group.
        /// </summary>
        Dictionary<int, IGeometry> GeometriesData { get; }

        /// <summary>
        /// Gets the maximum number of Geometries that can be stored in this Geometry Group.
        /// </summary>
        int GeometryCapacity { get; }

        /// <summary>
        /// Gets or sets whether the Geometry Group has skinning information.
        /// </summary>
        bool HasSkin { get; set; }

        /// <summary>
        /// Gets or sets whether the Geometry Group contains vertex color data.
        /// </summary>
        bool HasColors { get; set; }

        /// <summary>
        /// Gets or sets whether the Geometry Group contains invalid normals.
        /// </summary>
        bool HasInvalidNormals { get; set; }

        /// <summary>
        /// Gets or sets whether the Geometry Group contains valid normals.
        /// </summary>
        bool HasNormals { get; set; }

        /// <summary>
        /// Gets or sets whether the Geometry Group contains tangent data.
        /// </summary>
        bool HasTangents { get; set; }

        /// <summary>
        /// Gets or sets whether the Geometry Group contains a first UV set (UV1).
        /// </summary>
        bool HasUv1 { get; set; }

        /// <summary>
        /// Gets or sets whether the Geometry Group contains a second UV set (UV2).
        /// </summary>
        bool HasUv2 { get; set; }

        /// <summary>
        /// Gets or sets whether the Geometry Group contains a third UV set (UV3).
        /// </summary>
        bool HasUv3 { get; set; }

        /// <summary>
        /// Gets or sets whether the Geometry Group contains a fourth UV set (UV4).
        /// </summary>
        bool HasUv4 { get; set; }

        /// <summary>
        /// Gets or sets the final Unity <see cref="Mesh"/> generated by this Geometry Group.
        /// </summary>
        Mesh Mesh { get; set; }

        /// <summary>
        /// Gets or sets the position data for all vertices in this Geometry Group.
        /// </summary>
        List<Vector3> Positions { get; set; }

        /// <summary>
        /// Gets or sets the normal data for all vertices in this Geometry Group.
        /// </summary>
        List<Vector3> Normals { get; set; }

        /// <summary>
        /// Gets or sets the tangent data for all vertices in this Geometry Group.
        /// </summary>
        List<Vector4> Tangents { get; set; }

        /// <summary>
        /// Gets or sets the color data for all vertices in this Geometry Group.
        /// </summary>
        List<Color> Colors { get; set; }

        /// <summary>
        /// Gets or sets the first UV set (UV1) data for all vertices in this Geometry Group.
        /// </summary>
        List<Vector2> UVs1 { get; set; }

        /// <summary>
        /// Gets or sets the second UV set (UV2) data for all vertices in this Geometry Group.
        /// </summary>
        List<Vector2> UVs2 { get; set; }

        /// <summary>
        /// Gets or sets the third UV set (UV3) data for all vertices in this Geometry Group.
        /// </summary>
        List<Vector2> UVs3 { get; set; }

        /// <summary>
        /// Gets or sets the fourth UV set (UV4) data for all vertices in this Geometry Group.
        /// </summary>
        List<Vector2> UVs4 { get; set; }

        /// <summary>
        /// Gets/Sets this Geometry Group local pivot position.
        /// </summary>
        Vector3 Pivot { get; set; }

        /// <summary>
        /// Gets/Sets the Bone-Weights from this group.
        /// </summary>
        Dictionary<int, List<BoneWeight1>> RawBoneWeights { get; set; }

        /// <summary>
        /// Gets the maximum number of vertices that can be stored in this Geometry Group.
        /// </summary>
        int VerticesCapacity { get; }

        /// <summary>
        /// Gets the total number of vertex data items in the Geometry Group.
        /// </summary>
        int VerticesDataCount { get; }

        /// <summary>
        /// Gets or sets the list that maps the current vertex indices to the original vertex indices.
        /// </summary>
        List<int> OriginalVertexIndices { get; set; }

        /// <summary>
        /// Adds a new Bone Weight to this group.
        /// </summary>
        /// <param name="vertexIndex">The original Vertex index.</param>
        /// <param name="boneWeight1">The Bone Weight data.</param>
        void AddBoneWeight(int vertexIndex, BoneWeight1 boneWeight1);

        /// <summary>
        /// Adds or gets an existing Vertex to/from this Geometry Group.
        /// </summary>
        /// <param name="assetLoaderContext">The Asset Loader Context reference, containing model loading data.</param>
        /// <param name="vertexIndex">The original Vertex index.</param>
        /// <param name="position">The position of the vertex.</param>
        /// <param name="normal">The normal of the vertex.</param>
        /// <param name="tangent">The tangent of the vertex.</param>
        /// <param name="color">The color of the vertex.</param>
        /// <param name="uv1">The first UV set (UV1) coordinate.</param>
        /// <param name="uv2">The second UV set (UV2) coordinate.</param>
        /// <param name="uv3">The third UV set (UV3) coordinate.</param>
        /// <param name="uv4">The fourth UV set (UV4) coordinate.</param>
        /// <param name="boneWeight">The BoneWeight data.</param>
        /// <returns>The final vertex index in the Geometry Group.</returns>
        int AddVertex(
            AssetLoaderContext assetLoaderContext,
            int vertexIndex,
            Vector3 position,
            Vector3 normal,
            Vector4 tangent,
            Color color,
            Vector2 uv1,
            Vector2 uv2,
            Vector2 uv3,
            Vector2 uv4,
            BoneWeight boneWeight);

        /// <summary>
        /// Generates the final Unity Mesh.
        /// </summary>
        /// <param name="assetLoaderContext">The Asset Loader Context reference, containing model loading data.</param>
        /// <param name="meshGameObject">The GameObject the Mesh will be attached to.</param>
        /// <param name="meshModel">The geometry model reference.</param>
        /// <returns>An <see cref="IEnumerable"/> for asynchronous or deferred Mesh construction.</returns>
        IEnumerable GenerateMesh(
            AssetLoaderContext assetLoaderContext,
            GameObject meshGameObject,
            IModel meshModel);

        /// <summary>
        /// Computes the centroid (center) of all vertices in this Geometry Group.
        /// </summary>
        /// <returns>The centroid of the vertex positions.</returns>
        Vector3 GetCenter();

        /// <summary>
        /// Gets a new or existing Geometry from this group.
        /// </summary>
        /// <param name="assetLoaderContext">The Asset Loader Context reference, containing model loading data.</param>
        /// <param name="materialIndex">The Geometry Material index.</param>
        /// <param name="isQuad">Indicates if the Geometry contains quad data.</param>
        /// <param name="hasBlendShapes">Indicates if the Geometry uses blend-shapes.</param>
        /// <typeparam name="TGeometry">A class that implements <see cref="IGeometry"/>.</typeparam>
        /// <returns>A new or existing Geometry.</returns>
        TGeometry GetGeometry<TGeometry>(
            AssetLoaderContext assetLoaderContext,
            int materialIndex,
            bool isQuad,
            bool hasBlendShapes)
            where TGeometry : class, IGeometry, new();

        /// <summary>
        /// Configures this Geometry Group with capacity and context information.
        /// </summary>
        /// <param name="assetLoaderContext">The Asset Loader Context reference, containing model loading data.</param>
        /// <param name="verticesCapacity">The maximum number of vertices in this group.</param>
        /// <param name="geometriesCapacity">The maximum number of Geometries in this group.</param>
        void Setup(
            AssetLoaderContext assetLoaderContext,
            int verticesCapacity,
            int geometriesCapacity);

        /// <summary>
        /// Transfers this Geometry Group data to a Blend Shape, referencing another base Geometry Group.
        /// </summary>
        /// <param name="baseGeometryGroup">The base Geometry Group to transfer from.</param>
        /// <param name="blendShapeKey">The blend shape key to apply the transfer.</param>
        /// <param name="originalVertexIndices">A list of original vertex indices used for mapping data.</param>
        void TransferToBlendShape(
            IGeometryGroup baseGeometryGroup,
            IBlendShapeKey blendShapeKey,
            IList<int> originalVertexIndices);
    }
}
